name: Docker Image CI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set tag name
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: |
        echo "${{ secrets.GH_TOKEN }}" | docker login -u "${{ secrets.GH_USERNAME }}" --password-stdin ghcr.io
        docker build . --file Dockerfile --tag ghcr.io/naked-education/quiz:${{ env.RELEASE_VERSION }} --tag ghcr.io/naked-education/quiz:latest --build-arg APIKEY=${{ secrets.GH_TOKEN }}
        docker push ghcr.io/naked-education/quiz:${{ env.RELEASE_VERSION }}
        docker push ghcr.io/naked-education/quiz:latest
  deploy:

     needs: build_and_push
     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v2
     - name: Set tag name
       run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
     - name: Send webhook for deploy
       run: "curl --silent --show-error --fail -X POST portainer_path?tag=${{env.RELEASE_VERSION}}"
